# Generated by Django 3.0.14 on 2021-08-15 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg 파일을 업로드 해주세요.', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='번호 사이 -를 반드시 붙여주세요.', max_length=13, validators=[django.core.validators.RegexValidator('^010-[1-9]\\d{3}-\\d{4}$')]),
        ),
    ]
